import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Solveur Spectral Signé Higher-Order pour 3-SAT\n",
    "\n",
    "Ce notebook implémente et évalue un solveur spectral signé \"higher-order\" pour le problème 3-SAT, basé sur le document de spécification [main.md](file:///workspaces/3-SAT/SpectralHigherOrder/main.md).\n",
    "\n",
    "## 1. Principes Mathématiques de l'Approche Higher-Order\n",
    "Contrairement à l'approche spectrale classique qui relaxe les spins de sommets $\\sigma_i$, l'approche higher-order travaille dans l'espace des arêtes :\n",
    "1. **Encodage Exact** : Construction du graphe étendu ($V \\cup \\{T\\} \\cup S_C$) et compensation algébrique des poids d'arêtes signés.\n",
    "2. **Transfert LP** : Résolution d'un programme linéaire pour maximiser la part d'énergie transférée des arêtes vers les triangles.\n",
    "3. **Edge-space QP** : Résolution d'un programme quadratique convexe continu borné dans l'espace des arêtes avec régularisation de parité Hodge sur les triangles.\n",
    "4. **Synchronisation $\\mathbb{Z}_2$** : Projection du coloriage d'arêtes arrondi vers les spins des sommets via le Laplacien de synchronisation normalisé."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "# Installation de python-sat si nécessaire\n",
    "!pip install -q python-sat"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "import time\n",
    "import random\n",
    "import numpy as np\n",
    "import scipy.sparse\n",
    "import scipy.sparse.linalg\n",
    "from scipy.optimize import linprog, minimize\n",
    "import matplotlib.pyplot as plt\n",
    "from pysat.solvers import Glucose4\n",
    "\n",
    "print(\"Environnement importé avec succès.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Implémentation du Solveur"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "def recursive_unit_propagation_and_reductions(num_vars, clauses, active_vars=None, verbose=False):\n",
    "    fixed_literals = {}\n",
    "    active_clauses = [list(c) for c in clauses]\n",
    "    if active_vars is None:\n",
    "        active_vars = set(range(1, num_vars + 1))\n",
    "    else:\n",
    "        active_vars = set(active_vars)\n",
    "    fixed_empty_clauses = 0\n",
    "    \n",
    "    changed = True\n",
    "    while changed:\n",
    "        changed = False\n",
    "        empty_clauses = sum(1 for c in active_clauses if len(c) == 0)\n",
    "        if empty_clauses:\n",
    "            fixed_empty_clauses += empty_clauses\n",
    "            active_clauses = [c for c in active_clauses if len(c) > 0]\n",
    "        \n",
    "        unit_counts = {}\n",
    "        for c in active_clauses:\n",
    "            if len(c) == 1:\n",
    "                lit = c[0]\n",
    "                unit_counts[lit] = unit_counts.get(lit, 0) + 1\n",
    "                \n",
    "        if unit_counts:\n",
    "            var_unit_info = {}\n",
    "            for lit, count in unit_counts.items():\n",
    "                var = abs(lit)\n",
    "                pol = 1 if lit > 0 else -1\n",
    "                if var not in var_unit_info:\n",
    "                    var_unit_info[var] = {1: 0, -1: 0}\n",
    "                var_unit_info[var][pol] = count\n",
    "                \n",
    "            for var in sorted(list(var_unit_info.keys())):\n",
    "                info = var_unit_info[var]\n",
    "                pos_units = info[1]\n",
    "                neg_units = info[-1]\n",
    "                \n",
    "                if pos_units >= neg_units:\n",
    "                    l_val = 1\n",
    "                    m = pos_units\n",
    "                    opp_units = neg_units\n",
    "                else:\n",
    "                    l_val = -1\n",
    "                    m = neg_units\n",
    "                    opp_units = pos_units\n",
    "                    \n",
    "                opp_clauses_count = 0\n",
    "                for c in active_clauses:\n",
    "                    if len(c) >= 2:\n",
    "                        for lit in c:\n",
    "                            if abs(lit) == var:\n",
    "                                pol = 1 if lit > 0 else -1\n",
    "                                if pol != l_val:\n",
    "                                    opp_clauses_count += 1\n",
    "                                    break\n",
    "                                    \n",
    "                k = opp_clauses_count + opp_units\n",
    "                if m >= k:\n",
    "                    fixed_literals[var] = l_val\n",
    "                    active_vars.remove(var)\n",
    "                    new_active_clauses = []\n",
    "                    for c in active_clauses:\n",
    "                        satisfied = False\n",
    "                        for lit in c:\n",
    "                            if abs(lit) == var:\n",
    "                                pol = 1 if lit > 0 else -1\n",
    "                                if pol == l_val:\n",
    "                                    satisfied = True\n",
    "                                    break\n",
    "                        if not satisfied:\n",
    "                            new_clause = [lit for lit in c if abs(lit) != var]\n",
    "                            new_active_clauses.append(new_clause)\n",
    "                    active_clauses = new_active_clauses\n",
    "                    changed = True\n",
    "                    break\n",
    "            if changed:\n",
    "                continue\n",
    "                \n",
    "        # Pure literals\n",
    "        pos_counts = {v: 0 for v in active_vars}\n",
    "        neg_counts = {v: 0 for v in active_vars}\n",
    "        for c in active_clauses:\n",
    "            for lit in c:\n",
    "                var = abs(lit)\n",
    "                if var in active_vars:\n",
    "                    if lit > 0:\n",
    "                        pos_counts[var] += 1\n",
    "                    else:\n",
    "                        neg_counts[var] += 1\n",
    "                        \n",
    "        pure_vars = []\n",
    "        for var in list(active_vars):\n",
    "            pos = pos_counts[var]\n",
    "            neg = neg_counts[var]\n",
    "            if pos > 0 and neg == 0:\n",
    "                pure_vars.append((var, 1))\n",
    "            elif neg > 0 and pos == 0:\n",
    "                pure_vars.append((var, -1))\n",
    "            elif pos == 0 and neg == 0:\n",
    "                pure_vars.append((var, 1))\n",
    "                \n",
    "        if pure_vars:\n",
    "            changed = True\n",
    "            for var, val in pure_vars:\n",
    "                fixed_literals[var] = val\n",
    "                active_vars.remove(var)\n",
    "            new_active_clauses = []\n",
    "            for c in active_clauses:\n",
    "                satisfied = False\n",
    "                for lit in c:\n",
    "                    var = abs(lit)\n",
    "                    val = 1 if lit > 0 else -1\n",
    "                    if var in fixed_literals and fixed_literals[var] == val:\n",
    "                        satisfied = True\n",
    "                        break\n",
    "                if not satisfied:\n",
    "                    new_clause = [lit for lit in c if abs(lit) in active_vars]\n",
    "                    new_active_clauses.append(new_clause)\n",
    "            active_clauses = new_active_clauses\n",
    "            \n",
    "    return active_vars, active_clauses, fixed_literals, fixed_empty_clauses"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "def build_signed_graph_for_3sat(num_vars, active_vars, active_clauses, u=1.0):\n",
    "    var_list = sorted(list(active_vars))\n",
    "    var_to_idx = {v: i + 1 for i, v in enumerate(var_list)}\n",
    "    N_red = len(var_list)\n",
    "    \n",
    "    clause3_list = []\n",
    "    for c in active_clauses:\n",
    "        if len(c) == 3:\n",
    "            v1, v2, v3 = abs(c[0]), abs(c[1]), abs(c[2])\n",
    "            idx1, idx2, idx3 = var_to_idx[v1], var_to_idx[v2], var_to_idx[v3]\n",
    "            pol1 = 1 if c[0] > 0 else -1\n",
    "            pol2 = 1 if c[1] > 0 else -1\n",
    "            pol3 = 1 if c[2] > 0 else -1\n",
    "            lits = [(idx1, pol1), (idx2, pol2), (idx3, pol3)]\n",
    "            lits.sort(key=lambda x: x[0])\n",
    "            canonical_pair = (lits[0][0], lits[0][1], lits[1][0], lits[1][1])\n",
    "            clause3_list.append({\n",
    "                'idx': [idx1, idx2, idx3],\n",
    "                'pol': [pol1, pol2, pol3],\n",
    "                'canonical_pair': canonical_pair\n",
    "            })\n",
    "            \n",
    "    n_clause3 = len(clause3_list)\n",
    "    adj = {i: [] for i in range(n_clause3)}\n",
    "    for i in range(n_clause3):\n",
    "        for j in range(i + 1, n_clause3):\n",
    "            if clause3_list[i]['canonical_pair'] == clause3_list[j]['canonical_pair']:\n",
    "                adj[i].append(j)\n",
    "                adj[j].append(i)\n",
    "                \n",
    "    visited = [False] * n_clause3\n",
    "    components = []\n",
    "    for i in range(n_clause3):\n",
    "        if not visited[i]:\n",
    "            comp = []\n",
    "            queue = [i]\n",
    "            visited[i] = True\n",
    "            while queue:\n",
    "                curr = queue.pop(0)\n",
    "                comp.append(curr)\n",
    "                for neighbor in adj[curr]:\n",
    "                    if not visited[neighbor]:\n",
    "                        visited[neighbor] = True\n",
    "                        queue.append(neighbor)\n",
    "            components.append(comp)\n",
    "            \n",
    "    clause_to_merged_idx = {}\n",
    "    n_merged_nodes = len(components)\n",
    "    for comp_idx, comp in enumerate(components):\n",
    "        merged_node = N_red + 1 + comp_idx\n",
    "        for clause_idx in comp:\n",
    "            clause_to_merged_idx[clause_idx] = merged_node\n",
    "            \n",
    "    edges = []\n",
    "    clause3_counter = 0\n",
    "    for c in active_clauses:\n",
    "        if len(c) == 1:\n",
    "            lit = c[0]\n",
    "            v = abs(lit)\n",
    "            idx = var_to_idx[v]\n",
    "            pol = 1 if lit > 0 else -1\n",
    "            edges.append((idx, 0, u, pol))\n",
    "        elif len(c) == 2:\n",
    "            v1, v2 = abs(c[0]), abs(c[1])\n",
    "            idx1, idx2 = var_to_idx[v1], var_to_idx[v2]\n",
    "            pol1 = 1 if c[0] > 0 else -1\n",
    "            pol2 = 1 if c[1] > 0 else -1\n",
    "            edges.append((idx1, 0, u / 2.0, pol1))\n",
    "            edges.append((idx2, 0, u / 2.0, pol2))\n",
    "            edges.append((idx1, idx2, u / 2.0, -pol1 * pol2))\n",
    "        elif len(c) == 3:\n",
    "            info = clause3_list[clause3_counter]\n",
    "            idx1, idx2, idx3 = info['idx']\n",
    "            pol1, pol2, pol3 = info['pol']\n",
    "            s = clause_to_merged_idx[clause3_counter]\n",
    "            edges.append((idx1, 0, u / 2.0, pol1))\n",
    "            edges.append((idx2, 0, u / 2.0, pol2))\n",
    "            edges.append((idx3, 0, u / 2.0, pol3))\n",
    "            edges.append((s, idx1, u / 2.0, pol1))\n",
    "            edges.append((s, idx2, u / 2.0, pol2))\n",
    "            edges.append((s, idx3, u / 2.0, pol3))\n",
    "            edges.append((s, 0, u / 2.0, -1))\n",
    "            edges.append((idx1, idx2, u / 2.0, -pol1 * pol2))\n",
    "            edges.append((idx2, idx3, u / 2.0, -pol2 * pol3))\n",
    "            edges.append((idx1, idx3, u / 2.0, -pol1 * pol3))\n",
    "            clause3_counter += 1\n",
    "            \n",
    "    total_nodes = N_red + 1 + n_merged_nodes\n",
    "    A = np.zeros((total_nodes, total_nodes), dtype=np.float32)\n",
    "    for u_node, v_node, weight, sign in edges:\n",
    "        val = sign * weight\n",
    "        A[u_node, v_node] += val\n",
    "        A[v_node, u_node] += val\n",
    "    return A, var_to_idx"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "def find_triangles(A):\n",
    "    N = A.shape[0]\n",
    "    adj_sets = [set(np.where(A[r] != 0)[0]) for r in range(N)]\n",
    "    triangles = []\n",
    "    for u in range(N):\n",
    "        neighbors_u = np.where(A[u] != 0)[0]\n",
    "        neighbors_u = neighbors_u[neighbors_u > u]\n",
    "        for v in neighbors_u:\n",
    "            common = adj_sets[u].intersection(adj_sets[v])\n",
    "            for w in common:\n",
    "                if w > v:\n",
    "                    triangles.append((u, v, w))\n",
    "    return triangles"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "def transfer_weights_to_triangles(A, triangles):\n",
    "    N = A.shape[0]\n",
    "    edges_list = []\n",
    "    edge_to_idx = {}\n",
    "    for u in range(N):\n",
    "        for v in range(u + 1, N):\n",
    "            if A[u, v] != 0:\n",
    "                idx = len(edges_list)\n",
    "                edges_list.append((u, v))\n",
    "                edge_to_idx[(u, v)] = idx\n",
    "                \n",
    "    Ne = len(edges_list)\n",
    "    Nt = len(triangles)\n",
    "    W = np.array([abs(A[u, v]) for u, v in edges_list], dtype=np.float64)\n",
    "    \n",
    "    if Nt == 0:\n",
    "        return np.zeros(0), W, edges_list, edge_to_idx\n",
    "        \n",
    "    rows = []\n",
    "    cols = []\n",
    "    data = []\n",
    "    for t_idx, (i, j, k) in enumerate(triangles):\n",
    "        e1 = (i, j) if (i, j) in edge_to_idx else (j, i)\n",
    "        e2 = (j, k) if (j, k) in edge_to_idx else (k, j)\n",
    "        e3 = (i, k) if (i, k) in edge_to_idx else (k, i)\n",
    "        \n",
    "        rows.extend([edge_to_idx[e1], edge_to_idx[e2], edge_to_idx[e3]])\n",
    "        cols.extend([t_idx, t_idx, t_idx])\n",
    "        data.extend([1.0, 1.0, 1.0])\n",
    "        \n",
    "    M_sparse = scipy.sparse.coo_matrix((data, (rows, cols)), shape=(Ne, Nt))\n",
    "    \n",
    "    c = -np.ones(Nt, dtype=np.float64)\n",
    "    res = linprog(c, A_ub=M_sparse, b_ub=W, bounds=(0, None), method='highs')\n",
    "    if res.success:\n",
    "        omega = res.x\n",
    "    else:\n",
    "        omega = np.zeros(Nt, dtype=np.float64)\n",
    "        \n",
    "    rho = np.maximum(0.0, W - M_sparse.dot(omega))\n",
    "    return omega, rho, edges_list, edge_to_idx"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "def solve_edge_space_qp(A, omega, rho, edges_list, edge_to_idx, triangles, kappa=1.0):\n",
    "    Ne = len(edges_list)\n",
    "    Nt = len(triangles)\n",
    "    W = np.array([abs(A[u, v]) for u, v in edges_list], dtype=np.float64)\n",
    "    \n",
    "    if Ne == 0:\n",
    "        return np.zeros(0)\n",
    "    if Nt == 0:\n",
    "        return np.zeros(Ne)\n",
    "        \n",
    "    tri_edge_indices = []\n",
    "    b = np.zeros(Nt, dtype=np.float64)\n",
    "    \n",
    "    for t_idx, (i, j, k) in enumerate(triangles):\n",
    "        e1 = (i, j) if (i, j) in edge_to_idx else (j, i)\n",
    "        e2 = (j, k) if (j, k) in edge_to_idx else (k, j)\n",
    "        e3 = (i, k) if (i, k) in edge_to_idx else (k, i)\n",
    "        idx1 = edge_to_idx[e1]\n",
    "        idx2 = edge_to_idx[e2]\n",
    "        idx3 = edge_to_idx[e3]\n",
    "        tri_edge_indices.append((idx1, idx2, idx3))\n",
    "        \n",
    "        sign1 = np.sign(A[e1[0], e1[1]])\n",
    "        sign2 = np.sign(A[e2[0], e2[1]])\n",
    "        sign3 = np.sign(A[e3[0], e3[1]])\n",
    "        p_t = sign1 * sign2 * sign3\n",
    "        b[t_idx] = 0.5 * (1.0 - p_t)\n",
    "        \n",
    "    def objective(p):\n",
    "        obj = np.dot(W, p)\n",
    "        v = np.array([p[e1] + p[e2] + p[e3] for e1, e2, e3 in tri_edge_indices]) - b\n",
    "        obj += kappa * np.dot(omega, v**2)\n",
    "        return obj\n",
    "        \n",
    "    def gradient(p):\n",
    "        grad = W.copy()\n",
    "        v = np.array([p[e1] + p[e2] + p[e3] for e1, e2, e3 in tri_edge_indices]) - b\n",
    "        coeff = 2.0 * kappa * omega * v\n",
    "        for t_idx, (e1, e2, e3) in enumerate(tri_edge_indices):\n",
    "            c = coeff[t_idx]\n",
    "            grad[e1] += c\n",
    "            grad[e2] += c\n",
    "            grad[e3] += c\n",
    "        return grad\n",
    "        \n",
    "    p0 = np.zeros(Ne)\n",
    "    res = minimize(objective, x0=p0, jac=gradient, bounds=[(0.0, 1.0)]*Ne, method='L-BFGS-B')\n",
    "    return res.x"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "def project_edge_spins_to_vertices(A, p_opt, edges_list, y_cand, total_nodes):\n",
    "    W = np.array([abs(A[u, v]) for u, v in edges_list], dtype=np.float64)\n",
    "    c_e = W * np.abs(1.0 - 2.0 * p_opt)\n",
    "    \n",
    "    R = np.zeros((total_nodes, total_nodes), dtype=np.float64)\n",
    "    for idx, (u, v) in enumerate(edges_list):\n",
    "        epsilon_e = np.sign(A[u, v])\n",
    "        val = c_e[idx] * epsilon_e * y_cand[idx]\n",
    "        R[u, v] = val\n",
    "        R[v, u] = val\n",
    "        \n",
    "    d = np.sum(np.abs(R), axis=1)\n",
    "    if np.sum(d) < 1e-9:\n",
    "        return np.ones(total_nodes)\n",
    "        \n",
    "    d_inv_sqrt = np.zeros_like(d)\n",
    "    mask = d > 1e-9\n",
    "    d_inv_sqrt[mask] = 1.0 / np.sqrt(d[mask])\n",
    "    \n",
    "    D_inv_sqrt = scipy.sparse.diags(d_inv_sqrt)\n",
    "    D_sparse = scipy.sparse.diags(d)\n",
    "    L_sync = D_sparse - scipy.sparse.csc_matrix(R)\n",
    "    L_sync_norm = D_inv_sqrt @ L_sync @ D_inv_sqrt\n",
    "    \n",
    "    try:\n",
    "        if total_nodes <= 100:\n",
    "            eigenvalues, eigenvectors = np.linalg.eigh(L_sync_norm.toarray())\n",
    "            idx_min = np.argmin(eigenvalues)\n",
    "            v_min = eigenvectors[:, idx_min]\n",
    "        else: \n",
    "            eigenvalues, eigenvectors = scipy.sparse.linalg.eigsh(L_sync_norm, k=1, sigma=-1e-5, which='LM')\n",
    "            v_min = eigenvectors[:, 0]\n",
    "        v_min = D_inv_sqrt @ v_min\n",
    "    except Exception:\n",
    "        v_min = np.ones(total_nodes)\n",
    "        \n",
    "    aligned_spins = np.where(v_min >= 0, 1.0, -1.0)\n",
    "    aligned_spins = aligned_spins * (1.0 if v_min[0] >= 0 else -1.0)\n",
    "    aligned_spins[0] = 1.0\n",
    "    return aligned_spins"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "def extract_full_assignment(aligned_spins, var_to_idx, fixed_literals, num_vars):\n",
    "    spins = {}\n",
    "    for v in range(1, num_vars + 1):\n",
    "        if v in var_to_idx:\n",
    "            idx = var_to_idx[v]\n",
    "            spins[v] = int(aligned_spins[idx])\n",
    "        elif v in fixed_literals:\n",
    "            spins[v] = int(fixed_literals[v])\n",
    "        else: \n",
    "            spins[v] = 1\n",
    "    return spins\n",
    "\n",
    "def count_unsat_clauses(spins, clauses):\n",
    "    unsat_count = 0\n",
    "    for c in clauses:\n",
    "        sat = False\n",
    "        for lit in c:\n",
    "            var = abs(lit)\n",
    "            val = 1 if lit > 0 else -1\n",
    "            if spins[var] == val:\n",
    "                sat = True\n",
    "                break\n",
    "        if not sat:\n",
    "            unsat_count += 1\n",
    "    return unsat_count"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "def solve_3sat_spectral_higher_order(num_vars, clauses, u=1.0, kappa=1.0):\n",
    "    t_start = time.time()\n",
    "    \n",
    "    active_vars, active_clauses, fixed_literals, fixed_empty_clauses = \n",
    "        recursive_unit_propagation_and_reductions(num_vars, clauses)\n",
    "        \n",
    "    if len(active_vars) == 0:\n",
    "        spins = {v: fixed_literals.get(v, 1) for v in range(1, num_vars + 1)}\n",
    "        return spins, time.time() - t_start, fixed_empty_clauses\n",
    "        \n",
    "    A, var_to_idx = build_signed_graph_for_3sat(num_vars, active_vars, active_clauses, u=u)\n",
    "    total_nodes = A.shape[0]\n",
    "    \n",
    "    triangles = find_triangles(A)\n",
    "    omega, rho, edges_list, edge_to_idx = transfer_weights_to_triangles(A, triangles)\n",
    "    \n",
    "    p_opt = solve_edge_space_qp(A, omega, rho, edges_list, edge_to_idx, triangles, kappa=kappa)\n",
    "    \n",
    "    thresholds = np.linspace(0.05, 0.95, 20)\n",
    "    best_spins = None\n",
    "    best_unsat = len(clauses) + 1\n",
    "    \n",
    "    unique_y = []\n",
    "    for tau in thresholds:\n",
    "        y_cand = np.where(p_opt <= tau, 1, -1)\n",
    "        already_processed = False\n",
    "        for y_seen in unique_y:\n",
    "            if np.array_equal(y_cand, y_seen):\n",
    "                already_processed = True\n",
    "                break\n",
    "        if already_processed:\n",
    "            continue\n",
    "        unique_y.append(y_cand)\n",
    "        \n",
    "        aligned_spins = project_edge_spins_to_vertices(A, p_opt, edges_list, y_cand, total_nodes)\n",
    "        spins = extract_full_assignment(aligned_spins, var_to_idx, fixed_literals, num_vars)\n",
    "        unsat = count_unsat_clauses(spins, clauses)\n",
    "        \n",
    "        if unsat < best_unsat:\n",
    "            best_unsat = unsat\n",
    "            best_spins = spins\n",
    "            \n",
    "    t_elapsed = time.time() - t_start\n",
    "    return best_spins, t_elapsed, best_unsat"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Évaluation sur une Instance Générée (Circuit Miter)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "def generate_miter_circuit_3sat(n_inputs=15, n_gates=60, diff=\"Facile\", seed=42):\n",
    "    random.seed(seed)\n",
    "    clauses = []\n",
    "    next_var = n_inputs + 1\n",
    "    gates1 = []\n",
    "    gates2 = []\n",
    "    current_vars = list(range(1, n_inputs + 1))\n",
    "    for _ in range(n_gates):\n",
    "        gtype = random.choice([\"AND\", \"OR\", \"XOR\"])\n",
    "        in1 = random.choice(current_vars)\n",
    "        in2 = random.choice(current_vars)\n",
    "        out = next_var\n",
    "        next_var += 1\n",
    "        gates1.append((gtype, out, in1, in2))\n",
    "        current_vars.append(out)\n",
    "    output1 = current_vars[-1]\n",
    "    \n",
    "    n_mutations = 1 if diff == \"Facile\" else (2 if diff == \"Moyen\" else 4)\n",
    "    mutated_indices = set(random.sample(range(n_gates), min(n_mutations, n_gates)))\n",
    "    var_offset = next_var - (n_inputs + 1)\n",
    "    \n",
    "    for i, (gtype, out, in1, in2) in enumerate(gates1):\n",
    "        out2 = out + var_offset\n",
    "        in1_2 = in1 if in1 <= n_inputs else in1 + var_offset\n",
    "        in2_2 = in2 if in2 <= n_inputs else in2 + var_offset\n",
    "        if i in mutated_indices:\n",
    "            new_type = \"OR\" if gtype == \"AND\" else \"AND\"\n",
    "            gates2.append((new_type, out2, in1_2, in2_2))\n",
    "        else: \n",
    "            gates2.append((gtype, out2, in1_2, in2_2))\n",
    "            \n",
    "    output2 = current_vars[-1] + var_offset\n",
    "    next_var = output2 + 1\n",
    "    for g1, g2 in [(gates1, \"\"), (gates2, \"_2\")]:\n",
    "        for gtype, out, in1, in2 in g1:\n",
    "            if gtype == \"AND\":\n",
    "                clauses.append([in1, -out])\n",
    "                clauses.append([in2, -out])\n",
    "                clauses.append([-in1, -in2, out])\n",
    "            elif gtype == \"OR\":\n",
    "                clauses.append([-in1, out])\n",
    "                clauses.append([-in2, out])\n",
    "                clauses.append([in1, in2, -out])\n",
    "            elif gtype == \"XOR\":\n",
    "                clauses.append([-in1, -in2, -out])\n",
    "                clauses.append([in1, in2, -out])\n",
    "                clauses.append([-in1, in2, out])\n",
    "                clauses.append([in1, -in2, out])\n",
    "                \n",
    "    miter_out = next_var\n",
    "    clauses.append([-output1, -output2, -miter_out])\n",
    "    clauses.append([output1, output2, -miter_out])\n",
    "    clauses.append([-output1, output2, miter_out])\n",
    "    clauses.append([output1, -output2, miter_out])\n",
    "    clauses.append([miter_out])\n",
    "    return convert_to_3sat(miter_out, clauses)\n",
    "\n",
    "n_vars, clauses = generate_miter_circuit_3sat(15, 60, \"Facile\", seed=42)\n",
    "print(f\"Miter généré : {n_vars} variables, {len(clauses)} clauses.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "source": [
    "best_spins, t_ho, ho_unsat = solve_3sat_spectral_higher_order(n_vars, clauses)\n",
    "print(f\"HO Spectral Seul : Unsat = {ho_unsat} clauses non satisfaites en {t_ho:.4f} secondes.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

notebook_path = "/workspaces/3-SAT/SpectralHigherOrder/spectral_higher_order.ipynb"
with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)
print(f"Jupyter Notebook créé avec succès dans {notebook_path} !")
