import json
import os

def create_mcmc_notebook():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    mcmc_code_path = os.path.join(script_dir, "mcmc_higher_order.py")
    notebook_path = os.path.join(script_dir, "mcmc_higher_order.ipynb")
    
    # Read the mcmc_higher_order.py file
    if os.path.exists(mcmc_code_path):
        with open(mcmc_code_path, "r", encoding="utf-8") as f:
            mcmc_source_code = f.read()
    else:
        raise FileNotFoundError(f"Source file not found: {mcmc_code_path}")

    # Define cells
    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Analyse Comparative Exhaustive : Solveur MCMC Higher-Order pour 3-SAT\n",
                "\n",
                "Ce notebook implémente, évalue et analyse les performances d'un solveur MCMC **Higher-Order (HO)** par rapport à des solveurs CDCL (Glucose4), Max-SAT exacts (RC2), et WalkSAT pur (Random-start).\n",
                "\n",
                "## 1. Principes Algorithmiques & Mathématiques\n",
                "Le solveur MCMC Higher-Order résout le problème 3-SAT en se basant sur la physique statistique de la percolation :\n",
                "1. **Graphe Signé Étendu** : Représentation unifiée des clauses de taille 1, 2 et 3 à l'aide de poids signés et de variables auxiliaires.\n",
                "2. **Double Transfert d'Énergie** : Optimisation linéaire (LP) pour maximiser le transfert de poids des arêtes vers les triangles afin de capturer l'ordre supérieur.\n",
                "3. **Séparation de la température (`beta_T_factor`)** : Réduction par un facteur 10 du gel probabiliste des arêtes/triangles incidentes à la variable fantôme $T$ (champ externe). Cela évite le piège de la percolation complète ($K_T$) et préserve la mobilité des spins originaux.\n",
                "4. **Recherche Locale Réduite** : Identification des clusters flippables originaux et résolution locale du problème de spin-flip réduit via WalkSAT réduit (ou énumération exacte).\n",
                "5. **Warm-Start** : Initialisation de la recherche locale WalkSAT à partir de la configuration optimale fournie par MCMC HO.\n",
                "\n",
                "Ce notebook exécute l'analyse sur des benchmarks réels industriels (SAT Competition), académiques (SATLIB) et locaux (Circuit Miters)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Installation des bibliothèques nécessaires\n",
                "!pip install -q python-sat pandas matplotlib seaborn"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 2. Code Source du Solveur MCMC Higher-Order\n",
                "Le code ci-dessous correspond à l'implémentation complète du solveur (chargé dynamiquement depuis `mcmc_higher_order.py`)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                mcmc_source_code
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 3. Utilitaires de Chargement, Génération de Miters et Encodage"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import urllib.request\n",
                "import random\n",
                "import numpy as np\n",
                "import time\n",
                "\n",
                "COMPETITION_BENCHMARKS = {\n",
                "    \"xor6\": \"https://raw.githubusercontent.com/arminbiere/kissat/master/test/cnf/xor6.cnf\",\n",
                "    \"ph6\": \"https://raw.githubusercontent.com/arminbiere/kissat/master/test/cnf/ph6.cnf\",\n",
                "    \"miter1\": \"https://raw.githubusercontent.com/arminbiere/kissat/master/test/cnf/miter1.cnf\",\n",
                "    \"add32\": \"https://raw.githubusercontent.com/arminbiere/kissat/master/test/cnf/add32.cnf\",\n",
                "    \"prime169\": \"https://raw.githubusercontent.com/arminbiere/kissat/master/test/cnf/prime169.cnf\",\n",
                "    \"add64\": \"https://raw.githubusercontent.com/arminbiere/kissat/master/test/cnf/add64.cnf\",\n",
                "    \"prime841\": \"https://raw.githubusercontent.com/arminbiere/kissat/master/test/cnf/prime841.cnf\",\n",
                "    \"sqrt10609\": \"https://raw.githubusercontent.com/arminbiere/kissat/master/test/cnf/sqrt10609.cnf\"\n",
                "}\n",
                "\n",
                "def convert_to_3sat(num_vars, clauses):\n",
                "    final_cnf = []\n",
                "    next_var = num_vars + 1\n",
                "    for c in clauses:\n",
                "        if len(c) <= 3:\n",
                "            final_cnf.append(c)\n",
                "        else:\n",
                "            curr = c\n",
                "            while len(curr) > 3:\n",
                "                aux = next_var\n",
                "                next_var += 1\n",
                "                final_cnf.append([curr[0], curr[1], aux])\n",
                "                curr = [-aux] + curr[2:]\n",
                "            final_cnf.append(curr)\n",
                "    return next_var - 1, final_cnf\n",
                "\n",
                "def generate_miter_circuit_3sat(n_inputs=15, n_gates=60, diff=\"Facile\", seed=42):\n",
                "    random.seed(seed)\n",
                "    clauses = []\n",
                "    next_var = n_inputs + 1\n",
                "    gates1 = []\n",
                "    gates2 = []\n",
                "    \n",
                "    current_vars = list(range(1, n_inputs + 1))\n",
                "    for _ in range(n_gates):\n",
                "        gtype = random.choice([\"AND\", \"OR\", \"XOR\"])\n",
                "        in1 = random.choice(current_vars)\n",
                "        in2 = random.choice(current_vars)\n",
                "        out = next_var\n",
                "        next_var += 1\n",
                "        gates1.append((gtype, out, in1, in2))\n",
                "        current_vars.append(out)\n",
                "    output1 = current_vars[-1]\n",
                "    \n",
                "    n_mutations = 1 if diff == \"Facile\" else (2 if diff == \"Moyen\" else 4)\n",
                "    mutated_indices = set(random.sample(range(n_gates), min(n_mutations, n_gates)))\n",
                "    var_offset = next_var - (n_inputs + 1)\n",
                "    \n",
                "    for i, (gtype, out, in1, in2) in enumerate(gates1):\n",
                "        out2 = out + var_offset\n",
                "        in1_2 = in1 if in1 <= n_inputs else in1 + var_offset\n",
                "        in2_2 = in2 if in2 <= n_inputs else in2 + var_offset\n",
                "        if i in mutated_indices:\n",
                "            new_type = \"OR\" if gtype == \"AND\" else \"AND\"\n",
                "            gates2.append((new_type, out2, in1_2, in2_2))\n",
                "        else: \n",
                "            gates2.append((gtype, out2, in1_2, in2_2))\n",
                "            \n",
                "    output2 = current_vars[-1] + var_offset\n",
                "    next_var = output2 + 1\n",
                "    for g1, g2 in [(gates1, \"\"), (gates2, \"_2\")]:\n",
                "        for gtype, out, in1, in2 in g1:\n",
                "            if gtype == \"AND\":\n",
                "                clauses.append([in1, -out])\n",
                "                clauses.append([in2, -out])\n",
                "                clauses.append([-in1, -in2, out])\n",
                "            elif gtype == \"OR\":\n",
                "                clauses.append([-in1, out])\n",
                "                clauses.append([-in2, out])\n",
                "                clauses.append([in1, in2, -out])\n",
                "            elif gtype == \"XOR\":\n",
                "                clauses.append([-in1, -in2, -out])\n",
                "                clauses.append([in1, in2, -out])\n",
                "                clauses.append([-in1, in2, out])\n",
                "                clauses.append([in1, -in2, out])\n",
                "                \n",
                "    miter_out = next_var\n",
                "    clauses.append([-output1, -output2, -miter_out])\n",
                "    clauses.append([output1, output2, -miter_out])\n",
                "    clauses.append([-output1, output2, miter_out])\n",
                "    clauses.append([output1, -output2, miter_out])\n",
                "    clauses.append([miter_out])\n",
                "    return convert_to_3sat(miter_out, clauses)\n",
                "\n",
                "def parse_dimacs_content(content):\n",
                "    clauses = []\n",
                "    num_vars = 0\n",
                "    current_clause = []\n",
                "    for line in content.split('\\n'):\n",
                "        line = line.strip()\n",
                "        if not line or line.startswith('c'):\n",
                "            continue\n",
                "        if line.startswith('p cnf'):\n",
                "            parts = line.split()\n",
                "            num_vars = int(parts[2])\n",
                "            continue\n",
                "        for token in line.split():\n",
                "            val = int(token)\n",
                "            if val == 0:\n",
                "                if current_clause:\n",
                "                    clauses.append(current_clause)\n",
                "                    current_clause = []\n",
                "            else: \n",
                "                current_clause.append(val)\n",
                "    if current_clause:\n",
                "        clauses.append(current_clause)\n",
                "    return num_vars, clauses\n",
                "\n",
                "def download_benchmark(url):\n",
                "    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})\n",
                "    with urllib.request.urlopen(req, timeout=10) as response:\n",
                "        return response.read().decode('utf-8')\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 4. Baselines de Comparaison (CDCL, Max-SAT RC2, WalkSAT Pur)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from pysat.solvers import Glucose4\n",
                "from pysat.examples.rc2 import RC2\n",
                "from pysat.formula import WCNF\n",
                "\n",
                "def run_walksat(initial_spins, clauses, num_vars, max_flips=300000, p=0.3, max_time=10.0, target_unsat=0, seed=42):\n",
                "    random.seed(seed)\n",
                "    t_start = time.time()\n",
                "    spins = np.zeros(num_vars + 1, dtype=int)\n",
                "    for v in range(1, num_vars + 1):\n",
                "        if initial_spins is None or v not in initial_spins:\n",
                "            spins[v] = random.choice([-1, 1])\n",
                "        else:\n",
                "            spins[v] = initial_spins[v]\n",
                "        \n",
                "    pos_clauses = [[] for _ in range(num_vars + 1)]\n",
                "    neg_clauses = [[] for _ in range(num_vars + 1)]\n",
                "    for c_idx, c in enumerate(clauses):\n",
                "        for lit in c:\n",
                "            v = abs(lit)\n",
                "            if lit > 0:\n",
                "                pos_clauses[v].append(c_idx)\n",
                "            else:\n",
                "                neg_clauses[v].append(c_idx)\n",
                "                \n",
                "    num_satisfied = np.zeros(len(clauses), dtype=int)\n",
                "    unsat_list = []\n",
                "    clause_to_idx = np.full(len(clauses), -1, dtype=int)\n",
                "    \n",
                "    for c_idx, c in enumerate(clauses):\n",
                "        sat_count = sum(1 for lit in c if spins[abs(lit)] == (1 if lit > 0 else -1))\n",
                "        num_satisfied[c_idx] = sat_count\n",
                "        if sat_count == 0:\n",
                "            clause_to_idx[c_idx] = len(unsat_list)\n",
                "            unsat_list.append(c_idx)\n",
                "            \n",
                "    init_unsat = len(unsat_list)\n",
                "    if init_unsat <= target_unsat:\n",
                "        return {v: int(spins[v]) for v in range(1, num_vars + 1)}, init_unsat, time.time() - t_start, 0\n",
                "        \n",
                "    best_unsat = init_unsat\n",
                "    best_spins = spins.copy()\n",
                "    \n",
                "    flips_done = 0\n",
                "    for flip in range(1, max_flips + 1):\n",
                "        flips_done = flip\n",
                "        if not unsat_list or len(unsat_list) <= target_unsat:\n",
                "            break\n",
                "        if flip % 4000 == 0 and time.time() - t_start > max_time:\n",
                "            break\n",
                "            \n",
                "        c_idx = random.choice(unsat_list)\n",
                "        c = clauses[c_idx]\n",
                "        \n",
                "        if random.random() < p:\n",
                "            flip_var = abs(random.choice(c))\n",
                "        else: \n",
                "            best_diff = -1e9\n",
                "            best_vars = []\n",
                "            for lit in c:\n",
                "                v = abs(lit)\n",
                "                if spins[v] == 1:\n",
                "                    lose_clauses = pos_clauses[v]\n",
                "                    gain_clauses = neg_clauses[v]\n",
                "                else:\n",
                "                    lose_clauses = neg_clauses[v]\n",
                "                    gain_clauses = pos_clauses[v]\n",
                "                    \n",
                "                broken = sum(1 for tc_idx in lose_clauses if num_satisfied[tc_idx] == 1)\n",
                "                made = sum(1 for tc_idx in gain_clauses if num_satisfied[tc_idx] == 0)\n",
                "                \n",
                "                diff = made - broken\n",
                "                if diff > best_diff:\n",
                "                    best_diff = diff\n",
                "                    best_vars = [v]\n",
                "                elif diff == best_diff:\n",
                "                    best_vars.append(v)\n",
                "                    \n",
                "            flip_var = random.choice(best_vars)\n",
                "            \n",
                "        old_val = spins[flip_var]\n",
                "        new_val = -old_val\n",
                "        spins[flip_var] = new_val\n",
                "        \n",
                "        if old_val == 1:\n",
                "            lose_clauses = pos_clauses[flip_var]\n",
                "            gain_clauses = neg_clauses[flip_var]\n",
                "        else:\n",
                "            lose_clauses = neg_clauses[flip_var]\n",
                "            gain_clauses = pos_clauses[flip_var]\n",
                "            \n",
                "        for tc_idx in lose_clauses:\n",
                "            num_satisfied[tc_idx] -= 1\n",
                "            if num_satisfied[tc_idx] == 0:\n",
                "                if clause_to_idx[tc_idx] == -1:\n",
                "                    clause_to_idx[tc_idx] = len(unsat_list)\n",
                "                    unsat_list.append(tc_idx)\n",
                "                    \n",
                "        for tc_idx in gain_clauses:\n",
                "            if num_satisfied[tc_idx] == 0:\n",
                "                idx = clause_to_idx[tc_idx]\n",
                "                if idx != -1:\n",
                "                    last_c_idx = unsat_list[-1]\n",
                "                    unsat_list[idx] = last_c_idx\n",
                "                    clause_to_idx[last_c_idx] = idx\n",
                "                    unsat_list.pop()\n",
                "                    clause_to_idx[tc_idx] = -1\n",
                "            num_satisfied[tc_idx] += 1\n",
                "            \n",
                "        num_unsat = len(unsat_list)\n",
                "        if num_unsat < best_unsat:\n",
                "            best_unsat = num_unsat\n",
                "            best_spins = spins.copy()\n",
                "            if best_unsat <= target_unsat:\n",
                "                break\n",
                "                \n",
                "    t_elapsed = time.time() - t_start\n",
                "    best_spins_dict = {v: int(best_spins[v]) for v in range(1, num_vars + 1)}\n",
                "    return best_spins_dict, best_unsat, t_elapsed, flips_done\n",
                "\n",
                "def solve_with_glucose(num_vars, clauses):\n",
                "    t_start = time.time()\n",
                "    with Glucose4(bootstrap_with=clauses) as solver:\n",
                "        satisfied = solver.solve()\n",
                "    t_elapsed = time.time() - t_start\n",
                "    return \"SAT\" if satisfied else \"UNSAT\", t_elapsed\n",
                "\n",
                "def solve_maxsat_with_rc2(num_vars, clauses):\n",
                "    t_start = time.time()\n",
                "    if len(clauses) > 3000:\n",
                "        return \"Skip\", 0.0, -1\n",
                "    wcnf = WCNF()\n",
                "    for c in clauses:\n",
                "        wcnf.append(c, weight=1)\n",
                "    try:\n",
                "        with RC2(wcnf) as rc2:\n",
                "            model = rc2.compute()\n",
                "            t_elapsed = time.time() - t_start\n",
                "            if model is not None:\n",
                "                opt_unsat = rc2.cost\n",
                "                return f\"OPT: {opt_unsat}\", t_elapsed, opt_unsat\n",
                "    except Exception:\n",
                "        pass\n",
                "    return \"Error\", time.time() - t_start, -1\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 5. Exécution des Benchmarks et Visualisation Graphique des Performances\n",
                "Nous exécutons les tests sur une large variété d'instances (SAT Competition, Miters locaux de différentes tailles). Puis nous générons des graphiques analytiques détaillés."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import pandas as pd\n",
                "import matplotlib.pyplot as plt\n",
                "import seaborn as sns\n",
                "import torch\n",
                "\n",
                "def run_notebook_evaluation():\n",
                "    device = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
                "    print(f\"Device sélectionné pour PyTorch : {device} (GPU disponible : {torch.cuda.is_available()})\\n\")\n",
                "    \n",
                "    # Définition des benchmarks à tester\n",
                "    benchmarks_to_run = []\n",
                "    \n",
                "    # 1. Sélection de fichiers de la SAT Competition (téléchargés automatiquement)\n",
                "    instances = [\"xor6\", \"ph6\", \"prime169\", \"sqrt10609\"]\n",
                "    for key in instances:\n",
                "        url = COMPETITION_BENCHMARKS[key]\n",
                "        try:\n",
                "            print(f\"Téléchargement de l'instance Competition : {key}...\")\n",
                "            content = download_benchmark(url)\n",
                "            n_vars, clauses = parse_dimacs_content(content)\n",
                "            n_vars_3sat, clauses_3sat = convert_to_3sat(n_vars, clauses)\n",
                "            benchmarks_to_run.append((f\"Competition: {key}\", n_vars_3sat, clauses_3sat))\n",
                "        except Exception as e:\n",
                "            print(f\"  [ERREUR] Impossible de charger {key} ({e}).\")\n",
                "            \n",
                "    # 2. Ajout de circuits Miters de test (locaux)\n",
                "    benchmarks_to_run.append((\"Miter_Small (Local)\", *generate_miter_circuit_3sat(10, 40, \"Facile\", seed=100)))\n",
                "    benchmarks_to_run.append((\"Miter_Medium (Local)\", *generate_miter_circuit_3sat(30, 120, \"Moyen\", seed=101)))\n",
                "    benchmarks_to_run.append((\"Miter_Large (Local)\", *generate_miter_circuit_3sat(60, 250, \"Difficile\", seed=102)))\n",
                "    \n",
                "    results = []\n",
                "    \n",
                "    for name, n_vars, clauses in benchmarks_to_run:\n",
                "        n_clauses = len(clauses)\n",
                "        print(f\"\\nEvaluating {name} ({n_vars} variables, {n_clauses} clauses)...\\n\")\n",
                "        \n",
                "        # CDCL\n",
                "        glu_res, t_glu = solve_with_glucose(n_vars, clauses)\n",
                "        \n",
                "        # RC2 (MaxSAT)\n",
                "        rc2_res, t_rc2, rc2_unsat = solve_maxsat_with_rc2(n_vars, clauses)\n",
                "        \n",
                "        # Détermination de l'optimum global à viser\n",
                "        target_val = rc2_unsat if rc2_unsat >= 0 else (0 if glu_res == \"SAT\" else 1)\n",
                "        \n",
                "        # WalkSAT Pur\n",
                "        _, pure_unsat, t_pure, flips_pure = run_walksat(None, clauses, n_vars, target_unsat=target_val, max_time=10.0)\n",
                "        \n",
                "        # MCMC HO Seul\n",
                "        ho_spins, t_ho, ho_unsat = solve_3sat_mcmc_higher_order(n_vars, clauses, max_sweeps=150, verbose=False, device=device)\n",
                "        \n",
                "        # MCMC HO + WalkSAT\n",
                "        _, ho_walk_unsat, t_ho_walk, flips_ho_walk = run_walksat(ho_spins, clauses, n_vars, target_unsat=target_val, max_time=10.0)\n",
                "        t_total_ho_walk = t_ho + t_ho_walk\n",
                "        \n",
                "        # Calcul du gain en flips\n",
                "        flips_saved_pct = 0.0\n",
                "        if flips_pure > 0:\n",
                "            flips_saved_pct = ((flips_pure - flips_ho_walk) / flips_pure) * 100.0\n",
                "            \n",
                "        results.append({\n",
                "            \"Instance\": name,\n",
                "            \"Variables\": n_vars,\n",
                "            \"Clauses\": n_clauses,\n",
                "            \"Glucose\": glu_res,\n",
                "            \"Glucose Time (s)\": t_glu,\n",
                "            \"RC2 Unsat (Opt)\": rc2_unsat,\n",
                "            \"WalkSAT Pur Time (s)\": t_pure,\n",
                "            \"WalkSAT Pur Flips\": flips_pure,\n",
                "            \"MCMC HO Unsat\": ho_unsat,\n",
                "            \"MCMC HO Time (s)\": t_ho,\n",
                "            \"MCMC HO+WalkSAT Time (s)\": t_total_ho_walk,\n",
                "            \"MCMC HO+WalkSAT Flips\": flips_ho_walk,\n",
                "            \"Flips Saved (%)\": flips_saved_pct\n",
                "        })\n",
                "        \n",
                "    df = pd.DataFrame(results)\n",
                "    \n",
                "    # Affichage du tableau formaté sous forme de dégradé thermique\n",
                "    print(\"\\n=== TABLEAU DE SYNTHÈSE DES PERFORMANCES ===\")\n",
                "    display(df.style.background_gradient(subset=[\"Flips Saved (%)\"], cmap=\"RdYlGn\")\n",
                "                    .format({\"Glucose Time (s)\": \"{:.4f}\", \n",
                "                             \"WalkSAT Pur Time (s)\": \"{:.4f}\",\n",
                "                             \"MCMC HO Time (s)\": \"{:.4f}\",\n",
                "                             \"MCMC HO+WalkSAT Time (s)\": \"{:.4f}\",\n",
                "                             \"Flips Saved (%)\": \"{:.1f}%\"}))\n",
                "    \n",
                "    # Tracé des visualisations\n",
                "    sns.set_theme(style=\"whitegrid\")\n",
                "    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(18, 6), dpi=100)\n",
                "    \n",
                "    # Graphique 1 : Comparaison de temps\n",
                "    x = np.arange(len(df))\n",
                "    width = 0.35\n",
                "    ax1.bar(x - width/2, df[\"WalkSAT Pur Time (s)\"], width, label=\"WalkSAT Pur\", color=\"#f43f5e\")\n",
                "    ax1.bar(x + width/2, df[\"MCMC HO+WalkSAT Time (s)\"], width, label=\"MCMC HO + WalkSAT\", color=\"#3b82f6\")\n",
                "    ax1.set_title(\"Temps de résolution global (s)\", fontweight=\"bold\")\n",
                "    ax1.set_xticks(x)\n",
                "    ax1.set_xticklabels(df[\"Instance\"], rotation=30, ha=\"right\")\n",
                "    ax1.set_ylabel(\"Temps (secondes)\")\n",
                "    ax1.legend()\n",
                "    \n",
                "    # Graphique 2 : Flips sauvés (%)\n",
                "    ax2.bar(x, df[\"Flips Saved (%)\"], color=\"#10b981\", edgecolor=\"#047857\", width=0.5)\n",
                "    ax2.axhline(0, color=\"black\", linewidth=0.8, linestyle=\"--\")\n",
                "    ax2.set_title(\"Économie de Flips WalkSAT avec warm-start MCMC (%)\", fontweight=\"bold\")\n",
                "    ax2.set_xticks(x)\n",
                "    ax2.set_xticklabels(df[\"Instance\"], rotation=30, ha=\"right\")\n",
                "    ax2.set_ylabel(\"Flips Économisés (%)\")\n",
                "    \n",
                "    plt.tight_layout()\n",
                "    plt.show()\n",
                "\n",
                "run_notebook_evaluation()"
            ]
        }
    ]

    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 2
    }

    with open(notebook_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=1)
    print(f"Jupyter Notebook créé avec succès dans {notebook_path} !")

if __name__ == "__main__":
    create_mcmc_notebook()
